Milestone4 : desktop version
abdessalem1998/setup-and-mobile-version-skeleton pull request #4
Opened 2021-11-03 14:04 UTC by abdessalem1998

validate the work for the desktop version

2021-11-04 10:50 UTC, rotimiazeez requested changes
# Hi @abdessalem1998👋, 

### Good job so far!🔥🔥
### To Highlight 😎
-No Linter errors✔✔
- Descriptive README 👏👏
- Good PR description
#### There are some issues that you still need to work on to go to the next project but you are almost there!👍👍

#### Just a few changes and you'll be flying to the moon🚀😊

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- sticking to the design as much as possible (e.g., font, colours, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)😉😉✌

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 10:50 UTC, rotimiazeez commented on style.css
> +@media (min-width: 600px) {
- [ ] Please note that (the value for `min-width` property should be in range of `992px` - `1100px`)

2021-11-04 10:50 UTC, rotimiazeez commented on index.html
> +        <nav class="mobile">
- [ ] Kindly make sure your design matches your preferred Figma template design😎😎
- Your design 
![screenshot (2)](https://user-images.githubusercontent.com/44624138/140299816-edc5f64d-0c8f-4058-8702-b0b60b091e76.png)

- Figma design
![screenshot (1)](https://user-images.githubusercontent.com/44624138/140299541-2823ae08-b28c-413b-9d58-f0b1a20558e6.png)

2021-11-04 13:03 UTC, VanessaAoki requested changes
### STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @abdessalem1998 , 

Great work on making the changes requested by a previous reviewer, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


![really close](https://c.tenor.com/fuKjtbt7b4EAAAAd/really-really-close-bill-murray.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 13:03 UTC, VanessaAoki commented on style.css
> +  }
- [ ] In the desktop version there should be a line on top of the icons that strikes through the whole width of the page. You should also consider re-styling your icons, they have a background color.

Figma design:
![image](https://user-images.githubusercontent.com/66967274/140318093-004b5324-2e7f-4c01-b3e2-17e4befd7a74.png)

Your design:
![image](https://user-images.githubusercontent.com/66967274/140318049-e90b00be-56f7-4f66-8c22-7c4708c04a3f.png)

2021-11-04 13:24 UTC, abdessalem1998 commented on index.html
>                      <input class="contact-input" type="text" id="name" name="name" placeholder="username" maxlength="30" required>
[](url
![Capture106](https://user-images.githubusercontent.com/89970442/140320933-91123455-12f0-4cc8-9845-6278e76904d4.PNG)
)

2021-11-04 13:56 UTC, omar-labana commented
Hi @abdessalem1998, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where linters checks were not passing, also, please make sure to implement the changes requested by the previous reviewers.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-04 16:06 UTC, alonsofl requested changes
Hi @abdessalem1998,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 16:06 UTC, alonsofl commented on style.css
> +  .contact-form {
- [ ] You have done a good job by changing the layout for the desktop version but I think you could work a bit more to match the Figma design because the form and text sizes look as the mobile version. I would suggest adding some space between the elements and this section should take more width for the desktop version :smiley: 

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/140374983-e90369cb-1729-43d4-b119-6940cf40be68.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/140375027-5b268bd8-57b0-44d5-a5dc-fe76fe99341e.png)

2021-11-04 16:06 UTC, alonsofl commented on style.css
> +  .contact-icons {
- [ ] You have missed this change suggested by the previous reviewer :pushpin: I would suggest updating the icons styles according to the Figma design :raised_hands:

  Your design:
  ![image](https://user-images.githubusercontent.com/81522435/140375378-77b586fb-ecde-4172-b53a-adec46707bc8.png)

  Figma design:
  ![image](https://user-images.githubusercontent.com/81522435/140375459-7e026d18-7f01-4d95-a521-a9ab4a801d5f.png)

2021-11-05 16:45 UTC, MahmoudBakr23 reviewed
Hello @abdessalem1998 👋,

_This is an additional review as a result of the second opinion request._

**Thank you so much for your efforts so far! I know and I appreciate your hard work on this project, and you did a really great job on the required changes** It's approved now! ✅💪

### Important notes: ⚠️
- Please keep in mind that your design required many changes to match the given design in the first review. However, the CR requested a general requirement for you to follow the given design. Instead, they should've requested all the changes that should be fixed as the other CRs did in their reviews.🙏

_There are other optional requests!_

- Your design almost fully matches the given template. However, there are still some changes to be made! I highly suggest you go through the reviews and apply them.😄
- I have noticed that you have a broken MIT link in the README file, please fix it so that you have a 100% professional repo.😄

As this was the only reason that your project was not approved, it will be approved as soon as possible.
Please note that since we will approve it manually so this could take a few hours! 🙏 

Keep rocking 🚀!

2021-11-08 07:30 UTC, merged